### ISSUE TITLE
Tests Broken

### ISSUE THREAD

**Issue by heapwolf** [peerlinks/peerlinks#17]
I ran the tests and notice that there was an error...

```
  1) Invite
       should be requested, issued by issuer:
     TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined
      at Function.alloc (buffer.js:367:3)
      at new EphemeralBox (lib/utils.js:62:47)
      at Identity.requestInvite (lib/protocol/identity.js:238:17)
      at Context.<anonymous> (test/invite-test.js:31:42)
```

In the `EphemeralBox` implementation [`here`](https://github.com/peerlinks/peerlinks/blob/master/lib/utils.js#L62), it refers to `sodium.crypto_box_PUBLICKEYBYTES` which is not available in `sodium-universal`, only `sodium-native`,l according to [`this`](https://github.com/sodium-friends/sodium-universal#compatibilty) chart.

Did these tests pass at one point or were they a work in progress?

**Comment by heapwolf** [comment]
I Fixed the tests, I'll send a PR soon.
