### ISSUE TITLE
Peer errors with stale channels

### ISSUE THREAD

**Issue by indutny** [peerlinks/peerlinks#18]
```
 20:06:41.660 › 2020-05-15T03:06:41.660Z peerlinks:peer id=66705cfa:66 channel.id=5daa0a63/peerlinks:discuss sync error.message=Error: No valid identities to sync to the channel
[1]     at SyncAgent.findIdentityAndChain (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:241:13)
[1]     at SyncAgent.sendAndWait (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:255:38)
[1]     at SyncAgent.query (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:181:33)
[1]     at Channel.sync (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/protocol/channel.js:404:37)
[1]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[1]     at async SyncAgent.synchronize (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:82:19)
[1] 20:06:41.660 › 2020-05-15T03:06:41.660Z peerlinks:peer id=66705cfa:66 destroying due to reason=No valid identities to sync to the channel
[1] 20:06:41.660 › 2020-05-15T03:06:41.660Z peerlinks:sync-agent sync-agent.id=66705cfa:66/fdef7c64/aa destroy()
[1] 20:06:41.661 › 2020-05-15T03:06:41.661Z peerlinks:sync-agent sync-agent.id=66705cfa:66/ca2bbcbe/indutny:dev destroy()
[1] 20:06:41.661 › 2020-05-15T03:06:41.661Z peerlinks:sync-agent sync-agent.id=66705cfa:66/5daa0a63/peerlinks:discuss destroy()
[1] 20:06:41.662 › 2020-05-15T03:06:41.662Z peerlinks:peer id=66705cfa:66 got packet.type=error
[1] 20:06:41.662 › 2020-05-15T03:06:41.662Z peerlinks:protocol [bc1e8a48] got error: Error: Remote error: No valid identities to sync to the channel
[1]     at Peer.loop (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:234:15)
[1]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[1] 20:06:41.662 › 2020-05-15T03:06:41.662Z peerlinks:peer id=66705cfa:66 channel.id=fdef7c64/aa sync error.message=Error: SyncAgent destroyed
[1]     at SyncAgent.destroy (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:63:25)
[1]     at Peer.destroy (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:304:13)
[1]     at /Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:595:12
[1]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[1] 20:06:41.663 › 2020-05-15T03:06:41.663Z peerlinks:peer id=66705cfa:66 channel.id=ca2bbcbe/indutny:dev sync error.message=Error: SyncAgent destroyed
[1]     at SyncAgent.destroy (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/sync-agent.js:63:25)
[1]     at Peer.destroy (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:304:13)
[1]     at /Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:595:12
[1]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[1] 20:06:41.663 › 2020-05-15T03:06:41.663Z peerlinks-swarm connect() error Error: Already destroyed
[1]     at Peer.destroy (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/peer.js:287:13)
[1]     at Protocol.connect (/Users/findutnyy/Code/indutny/peerlinks-desktop/node_modules/@peerlinks/protocol/lib/protocol.js:503:18)
[1]     at processTicksAndRejections (internal/process/task_queues.js:89:5) ban=undefined
```

**Comment by indutny** [comment]
https://github.com/peerlinks/peerlinks/commit/79b70284b8d38a526b3f0c70b41cb4fc2cc89f9e
